version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_USER_SERVICE_URL=http://localhost:8081
      - REACT_APP_PRODUCT_SERVICE_URL=http://localhost:8082

  user-service:
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - MONGODB_URI=mongodb+srv://bader:blehaj123@cluster0.txyjrdn.mongodb.net/projet?retryWrites=true&w=majority&appName=Cluster0
      - TOKEN_SECRET_KEY=ffukufjkgfcxxsxtcdcvgeafefaefaefafaefthe
      - FRONTEND_URL=http://localhost:3000

  product-service:
    build:
      context: ./backend/product-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - MONGODB_URI=mongodb+srv://bader:blehaj123@cluster0.txyjrdn.mongodb.net/projet?retryWrites=true&w=majority&appName=Cluster0
      - TOKEN_SECRET_KEY=ffukufjkgfcxxsxtcdcvgeafefaefaefafaefthe
      - FRONTEND_URL=http://localhost:3000

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
